spring:
  main:
    web-application-type: NONE

logging:
  level:
    org.thingsboard.trendz.generator.service.rest.TbRestRequestInterceptor: INFO

tb:
  api:
    host:     "${GENERATOR_HOST:http://localhost:8080}"
    username: "${GENERATOR_USERNAME:solution.template.generator@thingsboard.io}"
    password: "${GENERATOR_PASSWORD:password}"
    pe:       "${GENERATOR_PE:false}"
    cloud:    "${GENERATOR_CLOUD:false}"

generator:
  mode: "${GENERATOR_MODE:generate}"  # generate, remove
  solutions: EnergyMetering, WaterMetering, Greenhouse
  skipTelemetry: false
  # true - run generator expecting no entities (when 'generate' mode) or expecting all entities (when 'remove' mode)
  # false - expecting that data is in inconsistent state
  strictGeneration: false
  startYear: 2023
  startGenerationTime: 1727740800000
  endGenerationTime: 1728345600000
  telemetryTtl: 315360000 # 10 years in seconds