server:
  port: 8887

tb:
  api:
    host:     http://localhost:8080
    username: solution.template.generator@thingsboard.io
    password: password
    pe:       false
    cloud:    false

generator:
  mode: "${GENERATOR_MODE:generate}"  # generate, remove
  solutions: Basic