spring:
  main:
    web-application-type: NONE

tb:
  api:
    host:     "${GENERATOR_HOST:http://localhost:8080}"
    username: "${GENERATOR_USERNAME:solution.template.generator@thingsboard.io}"
    password: "${GENERATOR_PASSWORD:password}"
    pe:       "${GENERATOR_PE:false}"
    cloud:    "${GENERATOR_CLOUD:false}"

generator:
  mode: "${GENERATOR_MODE:generate}"  # generate, remove
  solutions: EnergyMetering, WaterMetering
  skipTelemetry: false

  # true - run generator expecting no entities (when 'generate' mode) or expecting all entities (when 'remove' mode)
  # false - expecting that data is in inconsistent state
  strictGeneration: true

  # true - generate telemetry exactly from 'startGenerationTime' to 'endGenerationTime' and without generating anomalies
  # false - generate telemetry from static range in the code and with generating anomalies
  fullTelemetryGeneration: false
  startGenerationTime: 1672531200000
  endGenerationTime: 1893456000000
  telemetryTtl: 315360000 # 10 years in seconds